paths:
  data: data
  collections: content
  includes: themes/swingingGyropod/layouts
  layouts: themes/swingingGyropod/layouts
  static: themes/swingingGyropod/static
  uploads: static/uploads
  source: ''
  archetypes: archetypes
  assets: themes/swingingGyropod/assets
  content: content
  pages: themes/swingingGyropod/layouts/page
  publish: public
  config: ''
collections_config:
  Pages:
    path: themes/swingingGyropod/layouts/page
    output: true
    name: Pages
    icon: notes
    _editables:
      text:
        bold: true
        italic: true
        link: true
        redo: true
        removeformat: true
        undo: true
      content:
        image_size_attributes: true
        resize_style: contain
      image:
        correct_orientation: true
        image_size_attributes: true
        resize_style: contain
    _enabled_editors:
      - content
      - visual
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
editor: {}
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Europe/Paris
