paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: layouts/page
  publish: public
  config: ''
collections_config:
  pages:
    _enabled_editors:
      - visual
_enabled_editors:
  - content
  - visual
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Europe/Paris
