paths:
  data: data
  collections: content
  includes: themes/swingingGyropod/layouts
  layouts: themes/swingingGyropod/layouts
  static: themes/swingingGyropod/static
  uploads: static/uploads
  source: ''
  archetypes: archetypes
  assets: themes/swingingGyropod/assets
  content: content
  pages: themes/swingingGyropod/layouts/page
  publish: public
  config: ''
collections_config: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
editor: {}
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Europe/Paris
