baseURL = 'http://example.org/'
languageCode = 'fr'
defaultContentLanguage = 'fr'

[params]
GRADES = ["A", "B", "C", "D", "E", "F", "G"]
GES_CONVERTER = 0.216

[languages]
[languages.fr]
languageCode = "fr"
contentDir = 'content/french'
languageName = 'Français'
weight = 1
[languages.en]
languageCode = "en"
contentDir = 'content/english'
languageName = 'English'
weight = 2
